#!/bin/sh

clear; echo 'Running Alpine Labs flashloader' ;
echo 'Listening for Pulse connections via USB' ;
echo '' ;

while true; 
	do if [ `ls /media/pi/ | grep -i 'pulse' | wc -l`  = 1 ]; 
		then sleep 3; 
		echo 'Copying Firmware to Pulse. Please Wait...'; 
		cp /home/pi/Desktop/pulse_firmware.sb /media/pi/Pulse/; 
		sleep 15; echo 'Done Copying. You may remove Pulse.'; 
		echo '';
	fi; 
done

