#!/bin/sh

clear; echo 'Running Alpine Labs flashloader' ;
echo 'Listening for Pulse connections via USB' ;
echo '' ;

while true;
	do if [ `lsusb | grep Freescale | wc -l` = 1 ];
	  sudo mkdir /media/pi/Pulse;
		sudo mount -t vfat /dev/sda /media/pi/Pulse;
		then sleep 3;
		echo 'Copying Firmware to Pulse. Please Wait...';
		cp /home/pi/alpine_utilities/pulse-firmware.sb /media/pi/Pulse/;
		sleep 15; echo 'Done Copying. You may remove Pulse.';
		sudo umount /media/pi/Pulse;
		sudo rm /media/pi/Pulse;
		echo '';
	fi;
done
